### ISSUE TITLE
 fatal error: ros/world.h: No such file or directory

### ISSUE THREAD

**Issue by Yanxing-Shi** [qzlinqian/rrt_implement#1]
I meet the following mistakes：
```
/home/xingxing/catkin/src/rrt_implement/src/collision_detect.cpp:29:23: fatal error: ros/world.h: No such file or directory
compilation terminated.
```
please help me out

**Comment by qzlinqian** [comment]
Hi~ I'm so sorry for my late reply cause I forgot to watch this repo. Maybe you've already solved it.

I'm also very sorry that when I wrote this repo, I was a beginner of ROS and this package was poorly grouped, and there might be some redundant dependencies. This issue was caused by the node was compiled before the msg&srv generated. I have modified my CMakeLists.txt [here](https://github.com/qzlinqian/rrt_implement/commit/ec0277f8a933d30ae597adc4cf61af866532ed25) to compile the node after msg&srv are done.
